--- 
- 
  become: true
  hosts: elk
  name: "Configure Elk VM with Docker"
  remote_user: sysadmin
  tasks: 
    - 
      apt: 
        force_apt_get: true
        name: docker.io
        state: present
        update_cache: true
      name: "Install docker.io"
    - 
      apt: 
        force_apt_get: true
        name: pythin3-pip10
        state: present
      name: "Install python3-pip"
    - 
      name: "Install Docker module"
      pip: 
        name: docker
        state: present
    - 
      command: "sysctl -w vm.max_map_count=262144"
      name: "Increase virtual memory"
    - 
      name: "Use more memory"
      sysctl: 
        name: vm.max_map_count
        reload: true
        state: present
        value: "262144"
    - 
      docker_container: 
        image: "sebp/elk:761"
        name: elk
        published_ports: 
          - "5601:5601"
          - "9200:9200"
          - "5044:5044"
        restart_policy: always
        state: started
      name: "download and launch a docker elk container"
    - 
      name: "Enable service docker on boot"
      systemd: 
        enabled: true
        name: docker
